WIFI_SSID = ""
WIFI_PASSWORD = ""
HOSTNAME = "solar"
WIFI_COUNTRY = ""
REFRESH_WEBPAGE = 10

DEVICE_MAC = ""
DEVICE_ID = ""

METER_ENDPOINT = ""
METER_POWER_FIELD = "activePowerMin"
METER_POWER_DISPLAY_FIELD = "activePowerAvg"
POWER_LOWER_LIMIT = 0
POWER_UPPER_LIMIT = 100
